export default function Page() {
  return (
    <div>
      <p className="ml-8 mt-2">This is a hobby project.</p>
      <p className="ml-8">
        There is minimal logging used only for fixing bugs. No information is
        shared other than the stories are generated by ChatGPT using the OpenAI
        API
      </p>
    </div>
  );
}
